#!/bin/bash
# The single source of truth for the Exxos version number.
#
#   ./bump-version.sh              show it
#   ./bump-version.sh --patch      1.1.9  -> 1.1.10    every change
#   ./bump-version.sh --minor      1.1.10 -> 1.2.0     every push
#   ./bump-version.sh --major      1.2.0  -> 2.0.0     by hand only
#
# Three parts, and they mean different things:
#   MAJOR  a deliberate line in the sand -- a rebase onto a new Dolphin, or a
#          change that breaks how the thing is installed
#   MINOR  what is published: bumped by push-release.sh, so anyone reading a
#          version number can tell which published build they have
#   PATCH  local work between publishes
#
# Writing it in one place and generating from there stops the number in the
# title bar, the number in the package and the number in the tag drifting
# apart, which is the usual way version numbers stop being worth reading.
set -e
HERE="$(cd "$(dirname "$0")" && pwd)"
FILE="$HERE/VERSION"
[ -f "$FILE" ] || echo "1.0.0" > "$FILE"
V=$(tr -d ' \n' < "$FILE")

IFS=. read -r MAJ MIN PAT <<< "$V"
case "${MAJ}${MIN}${PAT}" in
    *[!0-9]*|"") echo "VERSION is not three numbers: '$V'" >&2; exit 1 ;;
esac

case "$1" in
    --patch) PAT=$((PAT + 1)) ;;
    --minor) MIN=$((MIN + 1)); PAT=0 ;;
    --major) MAJ=$((MAJ + 1)); MIN=0; PAT=0 ;;
    "")      echo "$V"; exit 0 ;;
    *)       echo "unknown option: $1" >&2; exit 1 ;;
esac

NEW="$MAJ.$MIN.$PAT"
echo "$NEW" > "$FILE"

# Regenerate the header the build reads, so the title bar cannot disagree.
cat > "$HERE/dolphin-src/src/exxosversion.h" <<EOF
/* GENERATED by bump-version.sh from theme-work/VERSION -- do not edit.
 *
 * The version shown in the window title and stamped into the package. Kept in
 * one place so the title bar, the .deb and the git tag cannot drift apart.
 */
#ifndef EXXOSVERSION_H
#define EXXOSVERSION_H
#define EXXOS_EDITION_VERSION "$NEW"
#endif
EOF

echo "$V -> $NEW"
