/* GENERATED by bump-version.sh from theme-work/VERSION -- do not edit.
 *
 * The version shown in the window title and stamped into the package. Kept in
 * one place so the title bar, the .deb and the git tag cannot drift apart.
 */
#ifndef EXXOSVERSION_H
#define EXXOSVERSION_H
#define EXXOS_EDITION_VERSION "1.8.9"
#endif
